## Pandas Data Frames

- What Is Pandas?
- Pandas vs Numpy 
- Pandas Data Frame Intro
- Pandas Data Frame fundamental operations
    - Creating
    - Selecting/indexing
    - Inserting rows/columns
    - Setting data
    - Filtering
    - dropping rwos/ columns
- Dealing with Missing values

%matplotlib inline
import numpy as np
import pandas as pd
from IPython.display import Image
from IPython.display import HTML
from IPython.display import Markdown, display
def printmd(string):
    display(Markdown(string))


CSS = """
.output {
    align-items: center;
}
"""
HTML('''<script>
code_show=true; 
function code_toggle() {
 if (code_show){
 $('div.input').hide();
 } else {
 $('div.input').show();
 }
 code_show = !code_show
} 
$( document ).ready(code_toggle);
</script>
<form action="javascript:code_toggle()"><input type="submit" value="Code mode"></form>''')

In [51]:
import pandas as pd
import numpy as np

from IPython.display import display, HTML

CSS = """
.output {
    align-items: center;
}
div.output_area {
    width: 80%;
}
"""
HTML('<style>{}</style>'.format(CSS))

# What is Pandas?

### - Enables working with tabular and labeled data easily and intuitively
### - Pandas is an open-source library built on top of Numpy Package.
- https://github.com/pandas-dev/pandas
- https://github.com/pandas-dev/pandas/blob/059c8bac51e47d6eaaa3e36d6a293a22312925e6/pandas/core/frame.py

### - Pandas data structures are:
    - Series
    - Index
    - Data Frame
    

## Quick refresh to Numpy Arrays..
- contains Numerical ***Homogonius*** Data
- may contain multi dimensional array elements.
- used for performing various numerical computations and processing of the multidimensional and single-dimensional array elements.

In [52]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

two_dim_arr = np.random.randint(10, size=(3, 4))  # Two-dimensional array
three_dim_arr = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
print(two_dim_arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


### A two dimensional Array example...

In [53]:
print("Two Dimentional Array")
two_dim_arr

Two Dimentional Array


array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

### What I mean by Homogeneous...

In [54]:
print(two_dim_arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


**two_dim_arr[0,0] = "Hello"**

In [55]:
printmd("***Oops....***")
two_dim_arr[0,0] = "Hello" 

NameError: name 'printmd' is not defined

### You can directly and simply form the DataFrame from the 2D array

In [ ]:
print("Data Frame formed by 2D Array")
printmd("***df=pd.DataFrame(two_dim_arr)***")
df=pd.DataFrame(two_dim_arr)
df

### Pandas Data Frame is Heterogeneous!
**df.iloc[0,0]="Hello"**

In [ ]:
df.iloc[0,0]="Hello"
df

### Pandas Data Frame labels the data with Indices and Columns labels
pd.DataFrame(np.random.randint(10,size=(3,2)),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

In [ ]:
np.random.randint(10,size=(3,2))

In [ ]:
##np.random.seed(0)
foo_df=pd.DataFrame(np.random.randint(10,size=(3,2)),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c']
                   )

In [ ]:
foo_df

foo_df.loc["a",:]

### Pandas DataFrame is relevant for statistical observations/data points with various variables (categorical, etc) 

In [ ]:
Image("res/Tidy_census.png")

### It is intuitive...  Look how convenient it is!!

In [ ]:
people_df= pd.read_csv("data/people.csv")
people_df

In [ ]:
Image('res/excel-to-pandas.png')

source: https://jalammar.github.io/

### Describing the Data Frame...
- df.Info()
- df.count())
- df.describe())
- df.mean())

In [ ]:
people_df

In [ ]:
people_df.iloc[0,1]=22
people_df

In [ ]:
people_df.loc[:,"age"].mean()

In [ ]:
people_df.age=people_df.age.astype(int)

In [ ]:
people_df.info()

In [ ]:
#print(df,"\n")
people_df.info()
#print("df.count()  \n",df.count())
#print("\n df.describe() \n",df.describe())
#print("\n df.mean() \n",df.mean())

In [ ]:
people_df.iloc[:,1]

In [ ]:
type(people_df.iloc[:,1])

In [ ]:
pd.Series([3,4,5])   ##. Pandas Series is a one dimentional data frame

### Pandas Data Frame operations

In [ ]:
Image("res/CRUD.png")

### Data Frame creation
You can create/form a Data Frame from:
- Dict of 1D ndarrays, lists, dicts, or Series

- 2-D numpy.ndarray

- Structured or record ndarray

- A Series

- Another DataFrame

#### Here is an example...

In [ ]:
print('dic = {"col1": [1.0, 2.0, 3.0, 4.0], "col2": [4.0, 3.0, 2.0, 1.0]}\n')

dic = {"col1": [1.0, 2.0, 3.0, 4.0], "col2": [4.0, 3.0, 2.0, 1.0]}

print("pd.DataFrame(dic)\n\n",pd.DataFrame(dic))

#### creating Index for the Data frame...

In [ ]:
print('pd.DataFrame(dic, index=["a", "b", "c", "d"]\n\n',
      pd.DataFrame(dic, index=["a", "b", "c", "d"]))

### Creating Data frame from Pandas Series objects.. 

In [ ]:
d = {
       "apples": pd.Series([3, 2, 0,1]),
        "oranges": pd.Series([0, 3, 7, 2]),
    }

pd.DataFrame(d)

In [ ]:
Image("res/series-and-dataframe.width-1200.png")

source: https://storage.googleapis.com/lds-media/images/series-and-dataframe.width-1200.png

### Data Frame Selection / Indexing

In [ ]:
data = {
    'name': ['Xavier', 'Ann', 'Jana', 'Yi', 'Robin', 'Amal', 'Nori'],
    'city': ['Mexico City', 'Toronto', 'Prague', 'Shanghai',
             'Manchester', 'Cairo', 'Osaka'],
    'age': [41, 28, 33, 34, 38, 31, 37],
    'py-score': [88.0, 79.0, 81.0, 80.0, 68.0, 61.0, 84.0]
}

row_labels = [101, 102, 103, 104, 105, 106, 107]
students_df = pd.DataFrame(data=data, index=row_labels)
students_df

In [ ]:
students_df.index

Source: https://realpython.com/

### data Selection

In [ ]:
students_df.loc[[101,102],["city","age"]]

In [ ]:
students_df

### Selecting by Label
- .loc[]  function

In [ ]:
#print("students_df.loc[:, 'city']")
#students_df.loc[:, 'city']

In [ ]:
print("students_df.loc[102:106, ['name', 'city']]")
students_df.loc[102,:]

In [ ]:
#print('df["city"]')
cities = students_df[["age","city"]]
cities

In [ ]:
print("df.city")
students_df.city

### Selecting by Position
- .iloc[]

In [ ]:
students_df.iloc[0,1]

In [ ]:
print("students_df.iloc[1:6, [0, 1]]")
students_df.iloc[1:6, [0, 1]]

### Hmm.. Can you tell what is the difference between loc and iloc?

#### You can use loc and iloc also to select certain data values but better to use at[] and iat[]

In [ ]:
print('df.at[103, name]')
students_df.at[103, 'name']

In [ ]:
print('df.iat[2, 0]')
students_df.iat[2, 0]

### Setting/ Updating data

#### let us first update the Data frame index..

In [ ]:
list(np.arange(10, 17))

In [ ]:
print ('df.index = np.arange(10, 17)')
students_df.index = list(np.arange(10, 17))
students_df

In [ ]:
students_df.index

In [ ]:
print('df.loc[:13, py-score] = [40, 50, 60, 70]')
students_df.loc[:13, 'py-score'] = [40, 50, 60, 70]
students_df

In [ ]:
print('df.loc[14:, py-score] = 0')
students_df.loc[14:, 'py-score'] = 70
students_df

In [ ]:
students_df.iloc[:, -1] = [88.0, 90, 81.0, 80.0, 68.0, 61.0, 84.0]
students_df

In [ ]:
students_df["py-score"]="Nina-score"
students_df

In [ ]:
students_df["py-score"]=students_df["py-score"]  * 1.5

In [ ]:
students_df

In [ ]:
students_df[["age","py-score"]].info()

In [ ]:
students_df["py-score"]=list(map(lambda x: x+10,students_df["py-score"]))

In [ ]:
students_df["py-score"]+=  10 

In [ ]:
students_df

In [ ]:
students_df.columns

### Inserting/deleteing rows

In [ ]:
Ronald = pd.Series(data=['Ronald', 'Berlin', 34, 79],
                 index=students_df.columns[0:4],name=21)

In [ ]:
Marcus = pd.Series(data=['Marcus', 'Berlin', 44, 75],
                 index=students_df.columns[0:4])

In [ ]:
students_df=students_df.append(Ronald)


In [ ]:
students_df

In [ ]:
#print('df = df.drop(labels=[17])')
students_df.drop(labels=[21],inplace=True)
students_df

In [333]:
students_df["py-score"]

10    88.0
11    90.0
12    81.0
13    80.0
14    68.0
15    61.0
16    84.0
Name: py-score, dtype: float64

### Inserting/Deleting columns

In [198]:
#print('df[js-score] = np.array([71.0, 95.0, 88.0, 79.0, 91.0, 91.0, 80.0])')
students_df['js-score'] =[71.0, 95.0, 88.0, 79.0, 91.0, 91.0, 80.0]
students_df

name         city  age  py-score  js-score
101  Xavier  Mexico City   41      88.0      71.0
102     Ann      Toronto   28      79.0      95.0
103    Jana       Prague   33      81.0      88.0
104      Yi     Shanghai   34      80.0      79.0
105   Robin   Manchester   38      68.0      91.0
106    Amal        Cairo   31      61.0      91.0
107    Nori        Osaka   37      84.0      80.0

### Inserting in a specific location

In [199]:
#print('df.insert(loc=4, column=js-score,value=np.array([86.0, 81.0, 78.0, 88.0, 74.0, 70.0, 81.0]))')
students_df.insert(loc=4, column='django-score',
          value=np.array([70, 74, 78, 56, 66, 78, 81.0]))
students_df

name         city  age  py-score  django-score  js-score
101  Xavier  Mexico City   41      88.0          70.0      71.0
102     Ann      Toronto   28      79.0          74.0      95.0
103    Jana       Prague   33      81.0          78.0      88.0
104      Yi     Shanghai   34      80.0          56.0      79.0
105   Robin   Manchester   38      68.0          66.0      91.0
106    Amal        Cairo   31      61.0          78.0      91.0
107    Nori        Osaka   37      84.0          81.0      80.0

### dropping specific column

In [200]:
print('df = df.drop(labels=age, axis=1)')
## axis= 0 dropping by row,  axis=1. ropping by column
students_df = students_df.drop(labels=['django-score'], axis=1)

df = df.drop(labels=age, axis=1)


In [201]:
students_df

name         city  age  py-score  js-score
101  Xavier  Mexico City   41      88.0      71.0
102     Ann      Toronto   28      79.0      95.0
103    Jana       Prague   33      81.0      88.0
104      Yi     Shanghai   34      80.0      79.0
105   Robin   Manchester   38      68.0      91.0
106    Amal        Cairo   31      61.0      91.0
107    Nori        Osaka   37      84.0      80.0

### Filtering/Boolean Indexing

In [342]:
#print('filter_ = df[django-score] >= 80')
very_good_students_filter = students_df['py-score'] >= 50
very_good_students_filter

10    True
11    True
12    True
13    True
14    True
15    True
16    True
Name: py-score, dtype: bool

In [205]:
students_df[students_df["py-score"]>=80]

name         city  age  py-score  js-score
101  Xavier  Mexico City   41      88.0      71.0
103    Jana       Prague   33      81.0      88.0
104      Yi     Shanghai   34      80.0      79.0
107    Nori        Osaka   37      84.0      80.0

In [206]:
students_df["js-score-updated"]= students_df["js-score"] + students_df["py-score"]  +5

In [207]:
students_df

name         city  age  py-score  js-score  js-score-updated
101  Xavier  Mexico City   41      88.0      71.0             164.0
102     Ann      Toronto   28      79.0      95.0             179.0
103    Jana       Prague   33      81.0      88.0             174.0
104      Yi     Shanghai   34      80.0      79.0             164.0
105   Robin   Manchester   38      68.0      91.0             164.0
106    Amal        Cairo   31      61.0      91.0             157.0
107    Nori        Osaka   37      84.0      80.0             169.0

In [208]:
students_df.age>40

101     True
102    False
103    False
104    False
105    False
106    False
107    False
Name: age, dtype: bool

In [349]:
students_df[students_df.age>40]

name         city  age  py-score  js-score  js-score-updated
10  Xavier  Mexico City   41      88.0      71.0              76.0

In [351]:
print('df[filter_]')
students_df[very_good_students_filter]

df[filter_]


name         city  age  py-score  js-score  js-score-updated
10  Xavier  Mexico City   41      88.0      71.0              76.0
11     Ann      Toronto   28      90.0      95.0             100.0
12    Jana       Prague   33      81.0      88.0              93.0
13      Yi     Shanghai   34      80.0      79.0              84.0
14   Robin   Manchester   38      68.0      91.0              96.0
15    Amal        Cairo   31      61.0      91.0              96.0
16    Nori        Osaka   37      84.0      80.0              85.0

### Creating powerful filters with Logical operators AND, OR, NOT, XOR

In [352]:
#print('df[(df[py-score] >= 80) & (df[js-score] >= 80)]')
students_df[(students_df['py-score'] >= 40) & (students_df['js-score'] >= 80)]

name        city  age  py-score  js-score  js-score-updated
11    Ann     Toronto   28      90.0      95.0             100.0
12   Jana      Prague   33      81.0      88.0              93.0
14  Robin  Manchester   38      68.0      91.0              96.0
15   Amal       Cairo   31      61.0      91.0              96.0
16   Nori       Osaka   37      84.0      80.0              85.0

### Working with Missing Data

### np.nan is used to represent missing values

In [210]:
print("df_ = pd.DataFrame({'x': [1, 2, np.nan, 4]})")
df_ = pd.DataFrame({'x': [1, 2, np.nan, 4]})
df_


df_ = pd.DataFrame({'x': [1, 2, np.nan, 4]})


x
0  1.0
1  2.0
2  NaN
3  4.0

In [211]:
df_["y"]=[2,np.nan,4,5]
df_

x    y
0  1.0  2.0
1  2.0  NaN
2  NaN  4.0
3  4.0  5.0

### Dropping rows that contains missing values 

In [235]:
#print("df_.dropna()")
df_.dropna()

Empty DataFrame
Columns: [x]
Index: []

### and you can fill the missing values with fillna..

In [219]:
df_ = pd.DataFrame({'x': [1, 2, np.nan, np.nan]})
print('df_.fillna(value=0)\n',df_.fillna(value=0))
print("\ndf_.fillna(method=ffill)\n",df_.fillna(method='ffill'))
print("\ndf_.fillna(method=bfill)\n",df_.fillna(method='bfill'))

df_.fillna(value=0)
      x
0  1.0
1  2.0
2  0.0
3  0.0

df_.fillna(method=ffill)
      x
0  1.0
1  2.0
2  2.0
3  2.0

df_.fillna(method=bfill)
      x
0  1.0
1  2.0
2  NaN
3  NaN


In [223]:
people_df

name  age country
0    Pol   22      ES
1   Javi   20      ES
2  Maria   23      AR
3   Anna   24      FR
4   Anna   24      UK
5   Javi   30      MA
6    Dog    2      XX

## Value_counts()  , describe()

In [222]:
people_df.name.value_counts()

Javi     2
Anna     2
Pol      1
Maria    1
Dog      1
Name: name, dtype: int64